export const GET_ITEMS = "GET_ITEMS"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const ADD_ITEMS_TO_CART = "ADD_ITEMS_TO_CART"
export const SET_LOADING = "SET_LOADING"
export const LOGIN_USER = "LOGIN_USER"
export const ITEMS_ERROR = "ITEMS_ERROR"
